### ISSUE TITLE
Implement OMDB

### ISSUE THREAD

**Issue by TheDoctor-95** [TheDoctor-95/FuryViewer#13]
Como IMDB esta caida implementamos otra api de pelis y series

# actualizacion
## Cosas a acabar

- [x] Import Guionista
- [x] Implementar Service artists i genres a Series

## Cosas a añadir/mejorar

- [x] En las funciones de `ArtistService`  cuando cogemos un artist desde nuestra BBDD comprovar que tenga el `ArtistType` corespondiente y añadirselo si hiciera falta
- [x] En las funciones de `ArtistService`  cuando añadimos un nuevo artist a la BBDD añadirle el `ArtistType` correspondiente
- [x] Añadir Import Company quando Importamos una pelicula (y no se si tambien en series), en caso de que sea en las 2 crer un `CompanyService`
- [x] En `Movie` y `Series` añadir los `Social` necesarios con las notas externas de la cada uno
- [x] En `importMovie` y `importSerie` hacer que si hay datos vacios no pete
- [x] Añadir comprobación "response: true" en todos los sitios donde se hacen peticiones a la api.
- [x] Comprovar numero capitulos correcto al importar
- [ ] Añadir imports por IMDB id
- [ ] Implementar search

**Comment by IFriedkin** [comment]
Pau y yo hemos trabajado juntos para implementar la api de OMDB.

**Comment by TheDoctor-95** [comment]
Como el PC de @Whoger  es una mierda, y tuvo que usar el mío al final me ha robado mi commit (maldito)

**Comment by IFriedkin** [comment]
Gracias a la ayuda de Alfredo, @TheDoctor-95 y yo pudimos desarrollar el service.

**Comment by TheDoctor-95** [comment]
Comit no vinculado a la Issue: d53df887832b05f021be8a12ac7e0e336e980327
