### ISSUE TITLE
Añadir Javadoc y comentarios

### ISSUE THREAD

**Issue by IFriedkin** [TheDoctor-95/FuryViewer#27]

**Comment by Whoger** [comment]
Dentro de services

- [x] ArtistBQueryService
- [x] ArtistServiceSmart
- [x] MovieQueryService
- [x] MovieServiceSmart
- [x] SeriesQueryService
- [x] SeriesServiceSmart

Dentro de services/dto

- [x] ArtistBCriteria
- [x] MovieBCriteria
- [x] SeriesBCriteria
